# Generated by Django 4.2.17 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
