# Generated by Django 4.2.17 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
