# Generated by Django 4.2.17 on 2026-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='required_ppe',
            field=models.JSONField(blank=True, default=list, help_text="PPE types the AI enforces for this camera, e.g. ['hardHat', 'vest', 'gloves', 'steelToedBoots']"),
        ),
    ]
