# Generated by Django 4.2.17 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_face_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='training_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
